/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Logo() {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/logo.glb");
  return (
    <group ref={group} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.003"]}
        position={[-0.35, 4.01, 6.65]}
        rotation={[0, 0, -1.03]}
        scale={[0.94, 1.33, 0.94]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[1.17, 4.95, 7.13]}
        scale={[1, 4.47, 1]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.002"]}
        position={[-2.38, 2.85, 7.22]}
        rotation={[0, 0, 0.01]}
        scale={[1, 4.47, 1]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.004"]}
        position={[-0.14, 4.16, 6.09]}
        rotation={[0, 0, -1.03]}
        scale={[0.94, 1.33, 0.94]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.005"]}
        position={[-1.07, 3.62, 6.09]}
        rotation={[0, 0, 2.1]}
        scale={[0.94, 1.33, 0.94]}
      />
    </group>
  );
}

useGLTF.preload("/assets/logo.glb");
